//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example.com/", ConfigurationName="ServiceReference1.ZodiacNameSoap")]
    public interface ZodiacNameSoap {
        
        // CODEGEN: Generating message contract since element name sign from namespace http://example.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/getZodiacDate", ReplyAction="*")]
        Client.ServiceReference1.getZodiacDateResponse getZodiacDate(Client.ServiceReference1.getZodiacDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/getZodiacDate", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.getZodiacDateResponse> getZodiacDateAsync(Client.ServiceReference1.getZodiacDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZodiacDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getZodiacDate", Namespace="http://example.com/", Order=0)]
        public Client.ServiceReference1.getZodiacDateRequestBody Body;
        
        public getZodiacDateRequest() {
        }
        
        public getZodiacDateRequest(Client.ServiceReference1.getZodiacDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/")]
    public partial class getZodiacDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sign;
        
        public getZodiacDateRequestBody() {
        }
        
        public getZodiacDateRequestBody(string sign) {
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZodiacDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getZodiacDateResponse", Namespace="http://example.com/", Order=0)]
        public Client.ServiceReference1.getZodiacDateResponseBody Body;
        
        public getZodiacDateResponse() {
        }
        
        public getZodiacDateResponse(Client.ServiceReference1.getZodiacDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/")]
    public partial class getZodiacDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getZodiacDateResult;
        
        public getZodiacDateResponseBody() {
        }
        
        public getZodiacDateResponseBody(string getZodiacDateResult) {
            this.getZodiacDateResult = getZodiacDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZodiacNameSoapChannel : Client.ServiceReference1.ZodiacNameSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZodiacNameSoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.ZodiacNameSoap>, Client.ServiceReference1.ZodiacNameSoap {
        
        public ZodiacNameSoapClient() {
        }
        
        public ZodiacNameSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZodiacNameSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiacNameSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiacNameSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.getZodiacDateResponse Client.ServiceReference1.ZodiacNameSoap.getZodiacDate(Client.ServiceReference1.getZodiacDateRequest request) {
            return base.Channel.getZodiacDate(request);
        }
        
        public string getZodiacDate(string sign) {
            Client.ServiceReference1.getZodiacDateRequest inValue = new Client.ServiceReference1.getZodiacDateRequest();
            inValue.Body = new Client.ServiceReference1.getZodiacDateRequestBody();
            inValue.Body.sign = sign;
            Client.ServiceReference1.getZodiacDateResponse retVal = ((Client.ServiceReference1.ZodiacNameSoap)(this)).getZodiacDate(inValue);
            return retVal.Body.getZodiacDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.getZodiacDateResponse> Client.ServiceReference1.ZodiacNameSoap.getZodiacDateAsync(Client.ServiceReference1.getZodiacDateRequest request) {
            return base.Channel.getZodiacDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.getZodiacDateResponse> getZodiacDateAsync(string sign) {
            Client.ServiceReference1.getZodiacDateRequest inValue = new Client.ServiceReference1.getZodiacDateRequest();
            inValue.Body = new Client.ServiceReference1.getZodiacDateRequestBody();
            inValue.Body.sign = sign;
            return ((Client.ServiceReference1.ZodiacNameSoap)(this)).getZodiacDateAsync(inValue);
        }
    }
}
