//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example.com/", ConfigurationName="ServiceReference1.ZodiacNameSoap")]
    public interface ZodiacNameSoap {
        
        // CODEGEN: Generating message contract since element name sign from namespace http://example.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/GetZodiacDate", ReplyAction="*")]
        Client.ServiceReference1.GetZodiacDateResponse GetZodiacDate(Client.ServiceReference1.GetZodiacDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/GetZodiacDate", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetZodiacDateResponse> GetZodiacDateAsync(Client.ServiceReference1.GetZodiacDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZodiacDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZodiacDate", Namespace="http://example.com/", Order=0)]
        public Client.ServiceReference1.GetZodiacDateRequestBody Body;
        
        public GetZodiacDateRequest() {
        }
        
        public GetZodiacDateRequest(Client.ServiceReference1.GetZodiacDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/")]
    public partial class GetZodiacDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sign;
        
        public GetZodiacDateRequestBody() {
        }
        
        public GetZodiacDateRequestBody(string sign) {
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZodiacDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZodiacDateResponse", Namespace="http://example.com/", Order=0)]
        public Client.ServiceReference1.GetZodiacDateResponseBody Body;
        
        public GetZodiacDateResponse() {
        }
        
        public GetZodiacDateResponse(Client.ServiceReference1.GetZodiacDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/")]
    public partial class GetZodiacDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetZodiacDateResult;
        
        public GetZodiacDateResponseBody() {
        }
        
        public GetZodiacDateResponseBody(string GetZodiacDateResult) {
            this.GetZodiacDateResult = GetZodiacDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZodiacNameSoapChannel : Client.ServiceReference1.ZodiacNameSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZodiacNameSoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.ZodiacNameSoap>, Client.ServiceReference1.ZodiacNameSoap {
        
        public ZodiacNameSoapClient() {
        }
        
        public ZodiacNameSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZodiacNameSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiacNameSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiacNameSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetZodiacDateResponse Client.ServiceReference1.ZodiacNameSoap.GetZodiacDate(Client.ServiceReference1.GetZodiacDateRequest request) {
            return base.Channel.GetZodiacDate(request);
        }
        
        public string GetZodiacDate(string sign) {
            Client.ServiceReference1.GetZodiacDateRequest inValue = new Client.ServiceReference1.GetZodiacDateRequest();
            inValue.Body = new Client.ServiceReference1.GetZodiacDateRequestBody();
            inValue.Body.sign = sign;
            Client.ServiceReference1.GetZodiacDateResponse retVal = ((Client.ServiceReference1.ZodiacNameSoap)(this)).GetZodiacDate(inValue);
            return retVal.Body.GetZodiacDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetZodiacDateResponse> Client.ServiceReference1.ZodiacNameSoap.GetZodiacDateAsync(Client.ServiceReference1.GetZodiacDateRequest request) {
            return base.Channel.GetZodiacDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetZodiacDateResponse> GetZodiacDateAsync(string sign) {
            Client.ServiceReference1.GetZodiacDateRequest inValue = new Client.ServiceReference1.GetZodiacDateRequest();
            inValue.Body = new Client.ServiceReference1.GetZodiacDateRequestBody();
            inValue.Body.sign = sign;
            return ((Client.ServiceReference1.ZodiacNameSoap)(this)).GetZodiacDateAsync(inValue);
        }
    }
}
