//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZodiacFinder.ServiceZN {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example.com/", ConfigurationName="ServiceZN.ZodiacNameSoap")]
    public interface ZodiacNameSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/getZodiacDate", ReplyAction="*")]
        ZodiacFinder.ServiceZN.getZodiacDateResponse getZodiacDate(ZodiacFinder.ServiceZN.getZodiacDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/getZodiacDate", ReplyAction="*")]
        System.Threading.Tasks.Task<ZodiacFinder.ServiceZN.getZodiacDateResponse> getZodiacDateAsync(ZodiacFinder.ServiceZN.getZodiacDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZodiacDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getZodiacDate", Namespace="http://example.com/", Order=0)]
        public ZodiacFinder.ServiceZN.getZodiacDateRequestBody Body;
        
        public getZodiacDateRequest() {
        }
        
        public getZodiacDateRequest(ZodiacFinder.ServiceZN.getZodiacDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/")]
    public partial class getZodiacDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sign;
        
        public getZodiacDateRequestBody() {
        }
        
        public getZodiacDateRequestBody(string sign) {
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZodiacDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getZodiacDateResponse", Namespace="http://example.com/", Order=0)]
        public ZodiacFinder.ServiceZN.getZodiacDateResponseBody Body;
        
        public getZodiacDateResponse() {
        }
        
        public getZodiacDateResponse(ZodiacFinder.ServiceZN.getZodiacDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/")]
    public partial class getZodiacDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getZodiacDateResult;
        
        public getZodiacDateResponseBody() {
        }
        
        public getZodiacDateResponseBody(string getZodiacDateResult) {
            this.getZodiacDateResult = getZodiacDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZodiacNameSoapChannel : ZodiacFinder.ServiceZN.ZodiacNameSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZodiacNameSoapClient : System.ServiceModel.ClientBase<ZodiacFinder.ServiceZN.ZodiacNameSoap>, ZodiacFinder.ServiceZN.ZodiacNameSoap {
        
        public ZodiacNameSoapClient() {
        }
        
        public ZodiacNameSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZodiacNameSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiacNameSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZodiacNameSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZodiacFinder.ServiceZN.getZodiacDateResponse getZodiacDate(ZodiacFinder.ServiceZN.getZodiacDateRequest request) {
            return base.Channel.getZodiacDate(request);
        }
        
        public System.Threading.Tasks.Task<ZodiacFinder.ServiceZN.getZodiacDateResponse> getZodiacDateAsync(ZodiacFinder.ServiceZN.getZodiacDateRequest request) {
            return base.Channel.getZodiacDateAsync(request);
        }
    }
}
