//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostcodeClient.PCFinder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example.com/", ConfigurationName="PCFinder.PostCodeFinderSoap")]
    public interface PostCodeFinderSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://example.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/GetPostCode", ReplyAction="*")]
        PostcodeClient.PCFinder.GetPostCodeResponse GetPostCode(PostcodeClient.PCFinder.GetPostCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example.com/GetPostCode", ReplyAction="*")]
        System.Threading.Tasks.Task<PostcodeClient.PCFinder.GetPostCodeResponse> GetPostCodeAsync(PostcodeClient.PCFinder.GetPostCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostCode", Namespace="http://example.com/", Order=0)]
        public PostcodeClient.PCFinder.GetPostCodeRequestBody Body;
        
        public GetPostCodeRequest() {
        }
        
        public GetPostCodeRequest(PostcodeClient.PCFinder.GetPostCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/")]
    public partial class GetPostCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetPostCodeRequestBody() {
        }
        
        public GetPostCodeRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostCodeResponse", Namespace="http://example.com/", Order=0)]
        public PostcodeClient.PCFinder.GetPostCodeResponseBody Body;
        
        public GetPostCodeResponse() {
        }
        
        public GetPostCodeResponse(PostcodeClient.PCFinder.GetPostCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://example.com/")]
    public partial class GetPostCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPostCodeResult;
        
        public GetPostCodeResponseBody() {
        }
        
        public GetPostCodeResponseBody(string GetPostCodeResult) {
            this.GetPostCodeResult = GetPostCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostCodeFinderSoapChannel : PostcodeClient.PCFinder.PostCodeFinderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostCodeFinderSoapClient : System.ServiceModel.ClientBase<PostcodeClient.PCFinder.PostCodeFinderSoap>, PostcodeClient.PCFinder.PostCodeFinderSoap {
        
        public PostCodeFinderSoapClient() {
        }
        
        public PostCodeFinderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostCodeFinderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostCodeFinderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostCodeFinderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PostcodeClient.PCFinder.GetPostCodeResponse PostcodeClient.PCFinder.PostCodeFinderSoap.GetPostCode(PostcodeClient.PCFinder.GetPostCodeRequest request) {
            return base.Channel.GetPostCode(request);
        }
        
        public string GetPostCode(string name) {
            PostcodeClient.PCFinder.GetPostCodeRequest inValue = new PostcodeClient.PCFinder.GetPostCodeRequest();
            inValue.Body = new PostcodeClient.PCFinder.GetPostCodeRequestBody();
            inValue.Body.name = name;
            PostcodeClient.PCFinder.GetPostCodeResponse retVal = ((PostcodeClient.PCFinder.PostCodeFinderSoap)(this)).GetPostCode(inValue);
            return retVal.Body.GetPostCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostcodeClient.PCFinder.GetPostCodeResponse> PostcodeClient.PCFinder.PostCodeFinderSoap.GetPostCodeAsync(PostcodeClient.PCFinder.GetPostCodeRequest request) {
            return base.Channel.GetPostCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostcodeClient.PCFinder.GetPostCodeResponse> GetPostCodeAsync(string name) {
            PostcodeClient.PCFinder.GetPostCodeRequest inValue = new PostcodeClient.PCFinder.GetPostCodeRequest();
            inValue.Body = new PostcodeClient.PCFinder.GetPostCodeRequestBody();
            inValue.Body.name = name;
            return ((PostcodeClient.PCFinder.PostCodeFinderSoap)(this)).GetPostCodeAsync(inValue);
        }
    }
}
